return {
    ["$metadata"] = {
        font = "normal",
        menu_spacing = 2,
        text_height = 6,
    },
    -- Please do not translate these and keep them in their original language ("english", "français", etc)
    lang_en = "english", 
    lang_fr = "français", 
    lang_zh = "中文", 
    lang_ja = "日本語",
    lang_ja_Hrkt = "にほんご",
    lang_ko = "한국어",

    menu_back = "もどる",

    menu_input_mode = "モード:",
    menu_input_mode_keyboard = "キーボード",
    menu_input_mode_mouse_keys = "マウス＋キー",
    menu_input_mode_gamepad = "ゲームパッド",

    menu_on = "オン",
    menu_off = "オフ",

    menu_continue = "つづける",
    menu_restart = "さいかい",
    menu_options = "せってい",
    menu_language = "げんご",
    menu_controls = "そうさ",
    menu_quit = "しゅうりょう",

    menu_sound = "おんせい",
    menu_volume = "おんりょう",
    menu_fullscreen = "ぜんがめん",

    menu_main = "タイトル",
    menu_main_random = "ランダム",

    menu_retry = "リトライ",
    menu_play_again = "もういちど",
    menu_change_bird = "とりをかえる",

    action_move = "いどう",
    action_left = "ひだり",
    action_right = "みぎ",
    action_up = "うえ",
    action_down = "した",
    action_shoot = "こうげき",
    action_change_weapon = "ぶきへんこう",
    action_weapon = "ぶき",

    credits_game_by = "せいさく:",
    credits_code = "コード",
    credits_art = "アート",
    credits_music = "おんがく",

    bird_pigeon = "ハト",
    bird_duck = "アヒル",
    bird_sparrow = "スズメ",
    bird_parrot = "オウム",
    bird_toucan = "オオハシ",
    bird_flamingo = "フラミンゴ",
    bird_eagle = "ワシ",
    bird_seagull = "カモメ",
    bird_ostrich = "ダチョウ",
    bird_penguin = "ペンギン",
    bird_jay = "カケス",
    bird_chicken = "ニワトリ",

    gun_revolver = "リボルバー",
    gun_firework_launcher = "はなびランチャー",
    gun_boxing_glove = "ボクシング",
    gun_bazooka = "バズーカ",
    gun_flamethrower = "かえんほうしゃき",
    gun_ring_cannon = "リングほう",
    gun_shotgun = "ショットガン",
    gun_machinegun = "マシンガン",
    gun_assault_rifle = "アサルト",
    gun_sniper = "スナイパー",
    gun_minigun = "ミニガン",

    stat_ammo = "だんやく",
    stat_health = "たいりょく",
    stat_wagon = "しゃりょう",
    stat_time = "じかん",
    stat_kills = "げきは",

    game_no_ammo = "だんぎれ！",
    game_over = "ゲームオーバー",
    game_win = "おめでとう！",
    game_win_subtext = "タイトルがめんで\n'i'をながおしで\nハードモードかいじょ",
    game_win_subtext_hard = "うそでしょ！？\nこのモード\nむりなはずだった！",
}
